// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Comprar passagem', function() {
  this.timeout(30000) // espera de 30mil milissegundos 
  let driver // objeto do selenium webdriver
  let vars // lista para guardar variaveis e informaçoes

  // antes de cada teste - inicialização - setup - config
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {} // inicializa a lista como vazia
  })

  // depois de cada teste
  afterEach(async function() {
    await driver.quit();
  })

  // o teste em sí
  it('Comprar passagem', async function() {
    await driver.get("https://www.blazedemo.com/")
    await driver.manage().window().setRect({ width: 1366, height: 728 })
    await driver.findElement(By.css("form")).click()
    await driver.findElement(By.name("fromPort")).click()
    {
      const dropdown = await driver.findElement(By.name("fromPort"))
      await dropdown.findElement(By.xpath("//option[. = 'São Paolo']")).click()
    }
    await driver.findElement(By.name("toPort")).click()
    {
      const dropdown = await driver.findElement(By.name("toPort"))
      await dropdown.findElement(By.xpath("//option[. = 'Cairo']")).click()
    }
    await driver.findElement(By.css(".btn-primary")).click()
    await driver.findElement(By.css("tr:nth-child(1) .btn")).click()
    await driver.findElement(By.id("inputName")).click()
    await driver.findElement(By.id("inputName")).sendKeys("Natalia")
    await driver.findElement(By.id("address")).sendKeys("BOTAFOGO")
    await driver.findElement(By.id("city")).sendKeys("RIO DE JANEIRO")
    await driver.findElement(By.id("state")).sendKeys("RJ")
    await driver.findElement(By.id("zipCode")).sendKeys("20240000")
    await driver.findElement(By.id("creditCardNumber")).sendKeys("123456")
    await driver.findElement(By.css("html")).click()
    await driver.findElement(By.id("creditCardMonth")).sendKeys("08")
    await driver.findElement(By.id("creditCardYear")).click()
    await driver.findElement(By.css("html")).click()
    await driver.findElement(By.id("creditCardYear")).sendKeys("1988")
    await driver.findElement(By.id("nameOnCard")).click()
    await driver.findElement(By.css("html")).click()
    await driver.findElement(By.id("nameOnCard")).sendKeys("NATALIA R")
    await driver.findElement(By.css(".btn-primary")).click()
    assert(await driver.findElement(By.css("h1")).getText() == "Thank you for your purchase today!")
    assert(await driver.findElement(By.css("tr:nth-child(3) > td:nth-child(2)")).getText() == "555 USD")
  })
})
